DROP DATABASE IF EXISTS testRatings;

CREATE DATABASE testRatings;

GRANT ALL PRIVILEGES ON testRatings.* to root@localhost IDENTIFIED BY 'root';

USE testRatings;

CREATE TABLE RATINGS (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	hall VARCHAR(256) NOT NULL,
	rating INT UNSIGNED NOT NULL,
	meal VARCHAR(256) NOT NULL,
	timeDate DATETIME NOT NULL
);

-- INSERT INTO RATINGS VaLUES (NULL, "Frary", 4, NULL);
-- INSERT INTO RATINGS VALUES (NULL, "CMC", 5,);
-- INSERT INTO RATINGS VALUES(NULL, "scripps", 5, NULL);
-- INSERT INTO RATINGS VALUES (NULL, "Pitzer", 4);
-- INSERT INTO RATINGS VALUES (NULL, "mudd", 5);
-- INSERT INTO RATINGS VALUES (NULL, "scripps", 5);
-- INSERT INTO RATINGS VALUES (NULL, "scripps", 4);
-- INSERT INTO RATINGS VALUES (NULL, "mudd", 3);
-- INSERT INTO RATINGS VALUES (NULL, "mudd", 5);
-- INSERT INTO RATINGS VALUES (NULL, "Pitzer", 4);
-- INSERT INTO RATINGS VALUES (NULL, "Frary", 1);
-- INSERT INTO RATINGS VALUES (NULL, "Frary", 4);
-- INSERT INTO RATINGS VALUES (NULL, "Frary", 5);